# Generated by Django 6.0.6 on 2026-08-03 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='duracao',
            field=models.PositiveIntegerField(),
        ),
    ]
