# Generated by Django 6.0.6 on 2026-08-10 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_servico_duracao'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='servicos/'),
        ),
    ]
