# Generated by Django 6.0.6 on 2026-09-11 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_agendamento_token_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
